apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicativo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aplicativo
  template:
    metadata:
      labels:
        app: aplicativo
    spec:
      containers:
      - name: aplicativo
        image: us-central1-docker.pkg.dev/aplicativo:0.1
